"""
CrowdAlert ORM model — mirrors frontend CrowdAlert interface.
Tracks alert lifecycle: OPEN → DISPATCHED → RESOLVED.
"""

from sqlalchemy import (
    String, Float, Text, DateTime, Enum as SAEnum, JSON, ForeignKey,
)
from sqlalchemy.orm import Mapped, mapped_column
from datetime import datetime, timezone
import enum
from app.db.base import Base
class AlertSeverity(str, enum.Enum):
    safe = "safe"
    caution = "caution"
    warning = "warning"
    critical = "critical"
class AlertStatus(str, enum.Enum):
    OPEN = "OPEN"
    DISPATCHED = "DISPATCHED"
    RESOLVED = "RESOLVED"
class CrowdAlert(Base):
    """
    A crowd safety alert generated by Sentinel AI or the rule-based risk engine.
    Maps to frontend `CrowdAlert` interface.
    """
    __tablename__ = "alerts"
    id: Mapped[str] = mapped_column(String(32), primary_key=True)  # e.g., "ALT-8924"
    zone_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("zones.id", ondelete="CASCADE"), nullable=False
    )
    venue_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("venues.id", ondelete="CASCADE"), nullable=False
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        SAEnum(AlertSeverity, name="alert_severity_enum", create_constraint=True),
        nullable=False,
        default=AlertSeverity.warning,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    category: Mapped[str] = mapped_column(
        String(100), nullable=False, default="Overcrowding",
        doc="Overcrowding | Gate Bottleneck | Sudden Surge | Sensor Anomaly | Medical Distress",
    )
    trigger_reason: Mapped[str] = mapped_column(Text, nullable=False, default="")
    sentinel_analysis: Mapped[str] = mapped_column(Text, nullable=False, default="")
    confidence_score: Mapped[float] = mapped_column(Float, default=0.0, doc="0-100 %")
    density: Mapped[float] = mapped_column(Float, default=0.0)
    flow_rate: Mapped[float] = mapped_column(Float, default=0.0)
    recommended_actions: Mapped[list | None] = mapped_column(
        JSON, nullable=True,
        doc='[{"id": "...", "actionText": "...", "impact": "...", "targetGateOrZone": "..."}]',
    )
    status: Mapped[AlertStatus] = mapped_column(
        SAEnum(AlertStatus, name="alert_status_enum", create_constraint=True),
        nullable=False,
        default=AlertStatus.OPEN,
    )
    suggested_action: Mapped[str] = mapped_column(String(500), nullable=False, default="")
    resolved_by: Mapped[str | None] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
